// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMinerStatus() {
  return window['go']['main']['App']['GetMinerStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartMining() {
  return window['go']['main']['App']['StartMining']();
}

export function StopMining() {
  return window['go']['main']['App']['StopMining']();
}
