// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ClearLogs():Promise<void>;

export function GetDefaultConfig():Promise<models.XMRigConfig>;

export function GetLogs():Promise<Array<string>>;

export function GetMinerStatus():Promise<models.MinerStatus>;

export function GetSystemInfo():Promise<models.SystemInfo>;

export function LoadConfig():Promise<models.XMRigConfig>;

export function SaveConfig(arg1:models.XMRigConfig):Promise<void>;

export function StartMining():Promise<void>;

export function StopMining():Promise<void>;
